listener 1883
protocol mqtt

persistence true
persistence_location /mosquitto/data/

log_dest stdout
log_type error
log_type warning
log_type notice
log_type information

# Authentication. The 'tesla' user is created by scripts/setup-broker-user.sh.
allow_anonymous false
password_file /mosquitto/config/passwd
